# Generated by Django 4.0.3 on 2023-05-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageunit',
            name='unitKey',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
