# Generated by Django 4.0.3 on 2023-05-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_storageunit_unitkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='remaining',
        ),
        migrations.RemoveField(
            model_name='products',
            name='total',
        ),
    ]
