# Generated by Django 4.0.3 on 2023-05-11 09:43

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_products_remaining_remove_products_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='shop',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='storedat',
            unique_together={('productId', 'storageId')},
        ),
    ]
