# Generated by Django 4.0.3 on 2023-05-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_invoice_shop_invoice_amount_invoice_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='created_at',
        ),
    ]
