# Generated by Django 4.0.3 on 2023-05-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_orderno_invoice_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
    ]
