# Generated by Django 4.0.3 on 2023-05-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_orders_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='code',
        ),
    ]
