# Generated by Django 4.0.3 on 2023-05-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_products_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
